{
  posts(
    where: {status: PUBLISHED},
    orderBy: createdAt_DESC
  ) {
    id,
    title,
    slug,
    dateAndTime,
    tags,
    postShortDescription,
    coverImage {
      id,
      url
    }
  }
}