{
  allPosts(
    filter: {isPublished: true},
    orderBy: createdAt_DESC
  ) {
    id,
    title,
    slug,
    dateAndTime,
    tags,
    postShortDescription,
    coverImage {
      id,
      url
    }
  }
}