{
  allPosts(
    filter: {isPublished: true},
    orderBy: createdAt_ASC
  ) {
    id,
    title,
    dateAndTime,
    slug,
    content,
    tags,
    authors {
      id,
      name,
      avatar {
        id,
        handle,
        url
      }
    }
  }
}